---
- name: Config file for mysql
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: Starting mysql
  service: name=mysqld state=restarted


- name: Mysql Configuration
  command: 'mysql -e "{{ item }}"'
  with_items:
    - CREATE DATABASE {{ master_db_name }};
    - create user '{{ user_name }}'@'%' identified by '{{ password }}';
    - grant replication slave on *.* to '{{ user_name }}'@'%';
    - update mysql.user set Repl_client_priv='Y' where user= '{{ user_name }}';
    - FLUSH PRIVILEGES;
    - STOP SLAVE;
    - CHANGE MASTER TO MASTER_HOST = '{{ master_ip }}', MASTER_USER = '{{ user_name }}', MASTER_PASSWORD = '{{ password }}', MASTER_LOG_FILE = 'master_log_file', MASTER_LOG_POS = master_log_pos;
    - START SLAVE;
 



