---
- name: Config file for mysql
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: Starting mysql
  service: name=mysqld state=restarted


- name: Create database user
  mysql_user: user={{ user_name }} password={{ password }} priv=*.*:ALL state=present


- name: Create database
  mysql_db: db={{ master_db_name }} state=present

- name: Mysql Configuration
  command: 'mysql -e "{{ item }}"'
  with_items:
    - grant replication slave on *.* to '{{ user_name }}'@'%';
    - update mysql.user set Repl_client_priv='Y' where user= '{{ user_name }}';
    - FLUSH PRIVILEGES;
 

- name: Config file for mysql
  template:
    src: sql.sh.j2
    dest: /root/sql.sh
    
- name: run the script
  command: bash /root/sql.sh 	

- name: copy a file from remote server
  fetch:
    src: /root/mysqloutput
    dest: /etc/ansible/roles/mysql-replication/mysql-master/templates/mysqloutput.j2
    flat: yes







